# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/narex/Dropbox/CoursM1/Synthese_image/Projet/Synthese_M1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/narex/Dropbox/CoursM1/Synthese_image/Projet/Synthese_M1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/narex/Dropbox/CoursM1/Synthese_image/Projet/Synthese_M1/CMakeFiles /home/narex/Dropbox/CoursM1/Synthese_image/Projet/Synthese_M1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/narex/Dropbox/CoursM1/Synthese_image/Projet/Synthese_M1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Synthese_Image

# Build rule for target.
Synthese_Image: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Synthese_Image
.PHONY : Synthese_Image

# fast build rule for target.
Synthese_Image/fast:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/build
.PHONY : Synthese_Image/fast

src/Camera.o: src/Camera.cpp.o
.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Cylinder.o: src/Cylinder.cpp.o
.PHONY : src/Cylinder.o

# target to build an object file
src/Cylinder.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Cylinder.cpp.o
.PHONY : src/Cylinder.cpp.o

src/Cylinder.i: src/Cylinder.cpp.i
.PHONY : src/Cylinder.i

# target to preprocess a source file
src/Cylinder.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Cylinder.cpp.i
.PHONY : src/Cylinder.cpp.i

src/Cylinder.s: src/Cylinder.cpp.s
.PHONY : src/Cylinder.s

# target to generate assembly for a file
src/Cylinder.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Cylinder.cpp.s
.PHONY : src/Cylinder.cpp.s

src/Gui.o: src/Gui.cpp.o
.PHONY : src/Gui.o

# target to build an object file
src/Gui.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Gui.cpp.o
.PHONY : src/Gui.cpp.o

src/Gui.i: src/Gui.cpp.i
.PHONY : src/Gui.i

# target to preprocess a source file
src/Gui.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Gui.cpp.i
.PHONY : src/Gui.cpp.i

src/Gui.s: src/Gui.cpp.s
.PHONY : src/Gui.s

# target to generate assembly for a file
src/Gui.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Gui.cpp.s
.PHONY : src/Gui.cpp.s

src/Light.o: src/Light.cpp.o
.PHONY : src/Light.o

# target to build an object file
src/Light.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Light.cpp.o
.PHONY : src/Light.cpp.o

src/Light.i: src/Light.cpp.i
.PHONY : src/Light.i

# target to preprocess a source file
src/Light.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Light.cpp.i
.PHONY : src/Light.cpp.i

src/Light.s: src/Light.cpp.s
.PHONY : src/Light.s

# target to generate assembly for a file
src/Light.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Light.cpp.s
.PHONY : src/Light.cpp.s

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Materiaux.o: src/Materiaux.cpp.o
.PHONY : src/Materiaux.o

# target to build an object file
src/Materiaux.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Materiaux.cpp.o
.PHONY : src/Materiaux.cpp.o

src/Materiaux.i: src/Materiaux.cpp.i
.PHONY : src/Materiaux.i

# target to preprocess a source file
src/Materiaux.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Materiaux.cpp.i
.PHONY : src/Materiaux.cpp.i

src/Materiaux.s: src/Materiaux.cpp.s
.PHONY : src/Materiaux.s

# target to generate assembly for a file
src/Materiaux.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Materiaux.cpp.s
.PHONY : src/Materiaux.cpp.s

src/Matrice.o: src/Matrice.cpp.o
.PHONY : src/Matrice.o

# target to build an object file
src/Matrice.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Matrice.cpp.o
.PHONY : src/Matrice.cpp.o

src/Matrice.i: src/Matrice.cpp.i
.PHONY : src/Matrice.i

# target to preprocess a source file
src/Matrice.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Matrice.cpp.i
.PHONY : src/Matrice.cpp.i

src/Matrice.s: src/Matrice.cpp.s
.PHONY : src/Matrice.s

# target to generate assembly for a file
src/Matrice.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Matrice.cpp.s
.PHONY : src/Matrice.cpp.s

src/Object.o: src/Object.cpp.o
.PHONY : src/Object.o

# target to build an object file
src/Object.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Object.cpp.o
.PHONY : src/Object.cpp.o

src/Object.i: src/Object.cpp.i
.PHONY : src/Object.i

# target to preprocess a source file
src/Object.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Object.cpp.i
.PHONY : src/Object.cpp.i

src/Object.s: src/Object.cpp.s
.PHONY : src/Object.s

# target to generate assembly for a file
src/Object.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Object.cpp.s
.PHONY : src/Object.cpp.s

src/PPMExporter.o: src/PPMExporter.cpp.o
.PHONY : src/PPMExporter.o

# target to build an object file
src/PPMExporter.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/PPMExporter.cpp.o
.PHONY : src/PPMExporter.cpp.o

src/PPMExporter.i: src/PPMExporter.cpp.i
.PHONY : src/PPMExporter.i

# target to preprocess a source file
src/PPMExporter.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/PPMExporter.cpp.i
.PHONY : src/PPMExporter.cpp.i

src/PPMExporter.s: src/PPMExporter.cpp.s
.PHONY : src/PPMExporter.s

# target to generate assembly for a file
src/PPMExporter.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/PPMExporter.cpp.s
.PHONY : src/PPMExporter.cpp.s

src/Parser.o: src/Parser.cpp.o
.PHONY : src/Parser.o

# target to build an object file
src/Parser.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Parser.cpp.o
.PHONY : src/Parser.cpp.o

src/Parser.i: src/Parser.cpp.i
.PHONY : src/Parser.i

# target to preprocess a source file
src/Parser.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Parser.cpp.i
.PHONY : src/Parser.cpp.i

src/Parser.s: src/Parser.cpp.s
.PHONY : src/Parser.s

# target to generate assembly for a file
src/Parser.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Parser.cpp.s
.PHONY : src/Parser.cpp.s

src/Point.o: src/Point.cpp.o
.PHONY : src/Point.o

# target to build an object file
src/Point.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Point.cpp.o
.PHONY : src/Point.cpp.o

src/Point.i: src/Point.cpp.i
.PHONY : src/Point.i

# target to preprocess a source file
src/Point.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Point.cpp.i
.PHONY : src/Point.cpp.i

src/Point.s: src/Point.cpp.s
.PHONY : src/Point.s

# target to generate assembly for a file
src/Point.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Point.cpp.s
.PHONY : src/Point.cpp.s

src/Ray.o: src/Ray.cpp.o
.PHONY : src/Ray.o

# target to build an object file
src/Ray.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Ray.cpp.o
.PHONY : src/Ray.cpp.o

src/Ray.i: src/Ray.cpp.i
.PHONY : src/Ray.i

# target to preprocess a source file
src/Ray.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Ray.cpp.i
.PHONY : src/Ray.cpp.i

src/Ray.s: src/Ray.cpp.s
.PHONY : src/Ray.s

# target to generate assembly for a file
src/Ray.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Ray.cpp.s
.PHONY : src/Ray.cpp.s

src/RayTracer.o: src/RayTracer.cpp.o
.PHONY : src/RayTracer.o

# target to build an object file
src/RayTracer.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/RayTracer.cpp.o
.PHONY : src/RayTracer.cpp.o

src/RayTracer.i: src/RayTracer.cpp.i
.PHONY : src/RayTracer.i

# target to preprocess a source file
src/RayTracer.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/RayTracer.cpp.i
.PHONY : src/RayTracer.cpp.i

src/RayTracer.s: src/RayTracer.cpp.s
.PHONY : src/RayTracer.s

# target to generate assembly for a file
src/RayTracer.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/RayTracer.cpp.s
.PHONY : src/RayTracer.cpp.s

src/Rectangle.o: src/Rectangle.cpp.o
.PHONY : src/Rectangle.o

# target to build an object file
src/Rectangle.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Rectangle.cpp.o
.PHONY : src/Rectangle.cpp.o

src/Rectangle.i: src/Rectangle.cpp.i
.PHONY : src/Rectangle.i

# target to preprocess a source file
src/Rectangle.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Rectangle.cpp.i
.PHONY : src/Rectangle.cpp.i

src/Rectangle.s: src/Rectangle.cpp.s
.PHONY : src/Rectangle.s

# target to generate assembly for a file
src/Rectangle.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Rectangle.cpp.s
.PHONY : src/Rectangle.cpp.s

src/Scene.o: src/Scene.cpp.o
.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i
.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s
.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/Shape.o: src/Shape.cpp.o
.PHONY : src/Shape.o

# target to build an object file
src/Shape.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Shape.cpp.o
.PHONY : src/Shape.cpp.o

src/Shape.i: src/Shape.cpp.i
.PHONY : src/Shape.i

# target to preprocess a source file
src/Shape.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Shape.cpp.i
.PHONY : src/Shape.cpp.i

src/Shape.s: src/Shape.cpp.s
.PHONY : src/Shape.s

# target to generate assembly for a file
src/Shape.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Shape.cpp.s
.PHONY : src/Shape.cpp.s

src/ShapeGenerator.o: src/ShapeGenerator.cpp.o
.PHONY : src/ShapeGenerator.o

# target to build an object file
src/ShapeGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/ShapeGenerator.cpp.o
.PHONY : src/ShapeGenerator.cpp.o

src/ShapeGenerator.i: src/ShapeGenerator.cpp.i
.PHONY : src/ShapeGenerator.i

# target to preprocess a source file
src/ShapeGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/ShapeGenerator.cpp.i
.PHONY : src/ShapeGenerator.cpp.i

src/ShapeGenerator.s: src/ShapeGenerator.cpp.s
.PHONY : src/ShapeGenerator.s

# target to generate assembly for a file
src/ShapeGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/ShapeGenerator.cpp.s
.PHONY : src/ShapeGenerator.cpp.s

src/Sphere.o: src/Sphere.cpp.o
.PHONY : src/Sphere.o

# target to build an object file
src/Sphere.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Sphere.cpp.o
.PHONY : src/Sphere.cpp.o

src/Sphere.i: src/Sphere.cpp.i
.PHONY : src/Sphere.i

# target to preprocess a source file
src/Sphere.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Sphere.cpp.i
.PHONY : src/Sphere.cpp.i

src/Sphere.s: src/Sphere.cpp.s
.PHONY : src/Sphere.s

# target to generate assembly for a file
src/Sphere.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Sphere.cpp.s
.PHONY : src/Sphere.cpp.s

src/Triangle.o: src/Triangle.cpp.o
.PHONY : src/Triangle.o

# target to build an object file
src/Triangle.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Triangle.cpp.o
.PHONY : src/Triangle.cpp.o

src/Triangle.i: src/Triangle.cpp.i
.PHONY : src/Triangle.i

# target to preprocess a source file
src/Triangle.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Triangle.cpp.i
.PHONY : src/Triangle.cpp.i

src/Triangle.s: src/Triangle.cpp.s
.PHONY : src/Triangle.s

# target to generate assembly for a file
src/Triangle.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Triangle.cpp.s
.PHONY : src/Triangle.cpp.s

src/Vector.o: src/Vector.cpp.o
.PHONY : src/Vector.o

# target to build an object file
src/Vector.cpp.o:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Vector.cpp.o
.PHONY : src/Vector.cpp.o

src/Vector.i: src/Vector.cpp.i
.PHONY : src/Vector.i

# target to preprocess a source file
src/Vector.cpp.i:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Vector.cpp.i
.PHONY : src/Vector.cpp.i

src/Vector.s: src/Vector.cpp.s
.PHONY : src/Vector.s

# target to generate assembly for a file
src/Vector.cpp.s:
	$(MAKE) -f CMakeFiles/Synthese_Image.dir/build.make CMakeFiles/Synthese_Image.dir/src/Vector.cpp.s
.PHONY : src/Vector.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Synthese_Image"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Cylinder.o"
	@echo "... src/Cylinder.i"
	@echo "... src/Cylinder.s"
	@echo "... src/Gui.o"
	@echo "... src/Gui.i"
	@echo "... src/Gui.s"
	@echo "... src/Light.o"
	@echo "... src/Light.i"
	@echo "... src/Light.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Materiaux.o"
	@echo "... src/Materiaux.i"
	@echo "... src/Materiaux.s"
	@echo "... src/Matrice.o"
	@echo "... src/Matrice.i"
	@echo "... src/Matrice.s"
	@echo "... src/Object.o"
	@echo "... src/Object.i"
	@echo "... src/Object.s"
	@echo "... src/PPMExporter.o"
	@echo "... src/PPMExporter.i"
	@echo "... src/PPMExporter.s"
	@echo "... src/Parser.o"
	@echo "... src/Parser.i"
	@echo "... src/Parser.s"
	@echo "... src/Point.o"
	@echo "... src/Point.i"
	@echo "... src/Point.s"
	@echo "... src/Ray.o"
	@echo "... src/Ray.i"
	@echo "... src/Ray.s"
	@echo "... src/RayTracer.o"
	@echo "... src/RayTracer.i"
	@echo "... src/RayTracer.s"
	@echo "... src/Rectangle.o"
	@echo "... src/Rectangle.i"
	@echo "... src/Rectangle.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/Shape.o"
	@echo "... src/Shape.i"
	@echo "... src/Shape.s"
	@echo "... src/ShapeGenerator.o"
	@echo "... src/ShapeGenerator.i"
	@echo "... src/ShapeGenerator.s"
	@echo "... src/Sphere.o"
	@echo "... src/Sphere.i"
	@echo "... src/Sphere.s"
	@echo "... src/Triangle.o"
	@echo "... src/Triangle.i"
	@echo "... src/Triangle.s"
	@echo "... src/Vector.o"
	@echo "... src/Vector.i"
	@echo "... src/Vector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

